import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, rm, stat } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { library } from "./library.mjs";
import { safeFile } from "./server.mjs";
test("library persists favorites, moves and restores only scoped images, and never overwrites", async t => {
  const dir = await mkdtemp(path.join(tmpdir(), "pocket-library-"));
  t.after(async () => { assert.ok(path.resolve(dir).startsWith(path.resolve(tmpdir()) + path.sep)); await rm(dir, { recursive: true, force: true }); });
  const output = path.join(dir, "output"), modelsRoot = path.join(dir, "Models");
  await mkdir(path.join(output, "nested"), { recursive: true }); await mkdir(path.join(modelsRoot, "StableDiffusion"), { recursive: true });
  await writeFile(path.join(output, "nested/lake.png"), "IMAGE");
  await writeFile(path.join(modelsRoot, "StableDiffusion", "lake.preview.jpeg"), "PREVIEW");
  const config = { roots: [{ name: "output", path: output }], stateDir: dir, modelsRoot };
  const lib = library(config, safeFile), item = { root: 0, relative: "nested/lake.png" };
  await Promise.all([lib.modelFavorite({ kind: "checkpoints", name: "lake.safetensors", favorite: true }), lib.modelFavorite({ kind: "loras", name: "film.safetensors", favorite: true })]);
  assert.deepEqual(await library(config, safeFile).modelFavorites(), { checkpoints: ["lake.safetensors"], loras: ["film.safetensors"] });
  await lib.modelFavorite({ kind: "loras", name: "film.safetensors", favorite: false });
  assert.deepEqual((await lib.modelFavorites()).loras, []);
  await assert.rejects(lib.modelFavorite({ kind: "invalid", name: "x", favorite: true }), { status: 400 });
  await lib.favorite({ ...item, favorite: true });
  assert.equal((await library(config, safeFile).decorate([item]))[0].favorite, true);
  assert.equal(await readFile(await lib.preview("checkpoints", "lake.safetensors"), "utf8"), "PREVIEW");
  await mkdir(path.join(modelsRoot, "Lora"), { recursive: true });
  await writeFile(path.join(modelsRoot, "Lora", "film.cm-info.json"), JSON.stringify({ ModelName: "Film", BaseModel: "SD 1.5", TrainedWords: ["film_grain"], ModelDescription: "<b>Texture</b>", PrivateField: "excluded" }));
  const metadata = await lib.modelInfo("loras", "film.safetensors");
  assert.equal(metadata.baseModel, "SD 1.5"); assert.deepEqual(metadata.triggers, ["film_grain"]); assert.equal(metadata.description, "Texture"); assert.equal(metadata.PrivateField, undefined);
  await assert.rejects(lib.modelInfo("loras", "../secret.safetensors"), { status: 403 });
  await writeFile(path.join(modelsRoot, "Lora", "bad.cm-info.json"), "{");
  await assert.rejects(lib.modelInfo("loras", "bad.safetensors"), { status: 422 });
  assert.deepEqual((await lib.modelInfo("loras", "missing.safetensors")).triggers, []);
  await assert.rejects(lib.preview("checkpoints", "../outside.safetensors"), { status: 403 });
  await assert.rejects(lib.trash({ root: 0, relative: "../outside.png" }), { status: 403 });
  const deleted = await lib.trash(item);
  await assert.rejects(stat(path.join(output, "nested/lake.png")), { code: "ENOENT" });
  assert.equal((await lib.trashList()).length, 1);
  await writeFile(path.join(output, "nested/lake.png"), "NEW");
  await assert.rejects(lib.restore(deleted), { status: 409 });
  assert.equal(await readFile(path.join(output, "nested/lake.png"), "utf8"), "NEW");
  await rm(path.join(output, "nested/lake.png"));
  await lib.restore(deleted);
  assert.equal(await readFile(path.join(output, "nested/lake.png"), "utf8"), "IMAGE");
  assert.equal((await lib.trashList()).length, 0);
  assert.equal((await lib.decorate([item]))[0].favorite, true);
});
