import { useEffect, useState } from "react";
import { Monitor, Plus, Pencil, Trash2, Link, FolderOpen, ShieldCheck, Unplug, Check } from "lucide-react";
import { native, parsePairing, type Pairing } from "./api";
import { LockSettings } from "./AppLock";
export interface ProfileInfo { id: string; name: string; url: string; active: boolean }
const blank = { url: "", token: "", certificate: "" };
export default function Connections({ server, busy, active, onConnect, onDisconnect, onError }: { server: string; busy: boolean; active: boolean; onConnect: (id: string) => Promise<void>; onDisconnect: (alreadyDisconnected?: boolean) => Promise<void>; onError: (e: string) => void }) {
  const [profiles, setProfiles] = useState<ProfileInfo[]>([]), [editing, setEditing] = useState<string | null>(null), [form, setForm] = useState(false), [name, setName] = useState(""), [pairing, setPairing] = useState<Pairing>(blank), [raw, setRaw] = useState(""), [working, setWorking] = useState(false);
  const load = async () => { const items = await native<ProfileInfo[]>("list_profiles"); setProfiles(items ?? []); if (!items?.length) setForm(true); };
  useEffect(() => { void load().catch(e => onError(String(e))); }, [server]);
  useEffect(() => { if (active && form && profiles.length) document.querySelector(".connection-form")?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [form, editing, active]);
  const run = async (fn: () => Promise<void>) => { setWorking(true); onError(""); try { await fn(); } catch (e) { onError(String(e)); } finally { setWorking(false); } };
  const fill = (text: string) => { const p = parsePairing(text); setPairing(p); setRaw(""); if (!name) setName("Mon PC"); };
  const save = async (connect: boolean) => run(async () => {
    const p = raw.trim() ? parsePairing(raw) : parsePairing(JSON.stringify(pairing));
    const id = await native<string>("save_profile", { id: editing, name: name.trim() || "Mon PC", pairing: p });
    if (profiles.find(v => v.id === editing)?.active) await onDisconnect(true);
    setForm(false); setEditing(null); setPairing(blank); setRaw(""); setName("");
    await load();
    if (connect) { await onConnect(id); await load(); }
  });
  return <div className="connections"><LockSettings /><section className="panel"><div className="section-heading"><div><span className="eyebrow">VOS ORDINATEURS</span><h2>Connexions</h2></div><button aria-label="Ajouter une connexion" onClick={() => { setEditing(null); setName(""); setPairing(blank); setRaw(""); setForm(true); }}><Plus /></button></div><p className="muted">Un profil pour chaque PC, ou pour ses adresses Wi-Fi et WireGuard.</p><div className="profile-list">{profiles.map(p => <article className={`profile-card ${p.active ? "selected" : ""}`} key={p.id}><div className="profile-title"><span className="icon-tile"><Monitor /></span><span><strong>{p.name}</strong><small>{p.url}</small></span>{p.active && <Check size={19} />}</div><div className="row"><button className={p.active ? "" : "primary"} disabled={busy || working} onClick={() => void onConnect(p.id).catch(e => onError(String(e)))}><Link size={16} />{p.active ? "Reconnecter" : "Connecter"}</button><button aria-label={`Modifier ${p.name}`} disabled={busy || working} onClick={() => void run(async () => { const full = await native<{ id: string; name: string; pairing: Pairing }>("get_profile", { id: p.id }); setEditing(p.id); setName(full.name); setPairing(full.pairing); setRaw(""); setForm(true); })}><Pencil size={18} /></button><button aria-label={`Supprimer le profil ${p.name}`} disabled={busy || working} onClick={() => void run(async () => { if (!confirm(`Supprimer le profil « ${p.name} » de cet appareil ?`)) return; await native("delete_profile", { id: p.id }); if (p.active) await onDisconnect(true); await load(); })}><Trash2 size={18} /></button></div></article>)}</div>{server && <button className="wide" disabled={busy || working} onClick={() => void onDisconnect().catch(e => onError(String(e)))}><Unplug size={17} /> Déconnecter</button>}</section>
  {form && <section className="panel connection-form"><div className="section-heading"><h2>{editing ? "Modifier la connexion" : "Ajouter un PC"}</h2>{profiles.length > 0 && <button onClick={() => { setForm(false); setPairing(blank); setRaw(""); }}>Fermer</button>}</div><label>Nom de la connexion<input value={name} maxLength={80} placeholder="PC maison · Wi-Fi" onChange={e => setName(e.target.value)} /></label><label className="file-picker"><FolderOpen size={19} /> Importer un fichier d’appairage<input type="file" accept=".json,application/json" onChange={e => { const file = e.target.files?.[0]; if (file) void run(async () => { if (file.size > 100000) throw new Error("Fichier d’appairage trop volumineux."); fill(await file.text()); }); e.target.value = ""; }} /></label><details><summary>Coller un fichier d’appairage</summary><label>Ou collez son contenu<textarea value={raw} rows={4} autoComplete="off" spellCheck={false} onChange={e => setRaw(e.target.value)} /></label><button disabled={!raw.trim()} onClick={() => { try { fill(raw); } catch (e) { onError(String(e)); } }}>Lire l’appairage</button></details><label>Adresse du PC<input type="url" value={pairing.url} placeholder="https://192.168.1.8:8189" autoCapitalize="none" spellCheck={false} onChange={e => setPairing(p => ({ ...p, url: e.target.value }))} /></label><label>Clé d’accès<input type="password" value={pairing.token} autoComplete="off" onChange={e => setPairing(p => ({ ...p, token: e.target.value }))} /></label><details><summary>Certificat du PC</summary><label>Certificat PEM<textarea value={pairing.certificate} rows={6} autoComplete="off" spellCheck={false} onChange={e => setPairing(p => ({ ...p, certificate: e.target.value }))} /></label></details><p className="hint"><ShieldCheck size={16} /> L’adresse doit être couverte par le certificat du PC. Le tunnel WireGuard reste géré par votre application VPN.</p><div className="row"><button disabled={working || busy} onClick={() => void save(false)}>Enregistrer</button><button className="primary" disabled={working || busy} onClick={() => void save(true)}><Link size={17} />{editing ? "Enregistrer et connecter" : "Connecter mon PC"}</button></div></section>}</div>;
}
