import { useEffect, useState } from "react";
import { Bookmark, Plus, Trash2, Pencil, Search, Upload, RotateCcw } from "lucide-react";
import { Modal, shortName } from "./components";
import { parsePreset, readPresets, writePresets, type InferencePreset } from "./presetStore";
import { losslessJson, type Settings } from "./workflow";
import type { Workflow } from "./api";
export default function Presets({ settings, mode, workflow, onApply }: { settings: Settings; mode: "simple" | "workflow"; workflow: Workflow | null; onApply: (preset: InferencePreset) => void }) {
  const [open, setOpen] = useState(false), [creating, setCreating] = useState(false), [name, setName] = useState(""), [items, setItems] = useState<InferencePreset[]>([]), [search, setSearch] = useState(""), [error, setError] = useState(""), [message, setMessage] = useState(""), [renaming, setRenaming] = useState<string | null>(null), [rename, setRename] = useState(""), [undo, setUndo] = useState<InferencePreset | null>(null);
  useEffect(() => { if (!message) return; const timer = setTimeout(() => setMessage(""), 6000); return () => clearTimeout(timer); }, [message]);
  const show = () => { setError(""); setMessage(""); try { setItems(readPresets()); } catch (e) { setError(String(e)); } setOpen(true); };
  const store = (next: InferencePreset[]) => { writePresets(next); setItems(next); };
  const action = (fn: () => void) => { setError(""); try { fn(); } catch (e) { setError(String(e)); } };
  const save = () => action(() => {
    const preset = parsePreset({ id: crypto.randomUUID(), name, settings, mode, workflow, createdAt: Date.now() });
    store([preset, ...items]); setName(""); setCreating(false); setMessage(`« ${preset.name} » enregistré.`);
  });
  return <><button onClick={show}><Bookmark size={17} /> Mes presets</button>{open && <Modal title="Mes presets" className="presets-page" onClose={() => setOpen(false)}>
    <div className="presets-content"><div className="preset-toolbar"><label className="search-box"><Search size={18} /><input aria-label="Rechercher un preset" value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher un preset…" /></label><button className="primary" disabled={mode === "workflow" && !workflow} onClick={() => { setName(""); setError(""); setCreating(true); }}><Plus size={18} /> Nouveau preset</button></div>
    {mode === "workflow" && !workflow && <p className="hint">Validez le workflow API avant de l’enregistrer.</p>}{error && !creating && <p role="alert">{error}</p>}
    <div className="inference-presets">{items.filter(p => p.name.toLowerCase().includes(search.toLowerCase())).map(p => <article className="inference-preset" key={p.id}>{renaming === p.id ? <div className="preset-rename"><label>Nouveau titre<input autoFocus maxLength={80} value={rename} onChange={e => setRename(e.target.value)} /></label><button disabled={!rename.trim()} onClick={() => action(() => { store(items.map(i => i.id === p.id ? { ...i, name: rename.trim() } : i)); setRenaming(null); })}>Valider le titre</button><button onClick={() => setRenaming(null)}>Annuler</button></div> : <><button className="preset-load" aria-label={`Charger ${p.name}`} onClick={() => { onApply(parsePreset(p)); setOpen(false); }}><Bookmark size={20} /><span><strong>{p.name}</strong><small>{p.mode === "workflow" ? "Workflow API" : shortName(p.settings.model)} · {p.settings.width} × {p.settings.height}</small><small>{p.settings.steps} steps · {p.settings.loras.length} LoRA · {p.settings.hires.enabled ? "Hires Fix" : "Sans Hires Fix"}</small></span></button><div className="preset-tools"><button aria-label={`Renommer ${p.name}`} onClick={() => { setRenaming(p.id); setRename(p.name); }}><Pencil size={17} /></button><button aria-label={`Supprimer le preset ${p.name}`} onClick={() => action(() => { store(items.filter(i => i.id !== p.id)); setUndo(p); setMessage("Preset supprimé."); })}><Trash2 size={17} /></button></div></>}</article>)}</div>
    {!items.length && <div className="preset-empty"><Bookmark size={34} /><p>Vos réglages favoris, prêts à être retrouvés.</p></div>}
    <label className="file-picker"><Upload size={17} /> Importer un preset JSON<input type="file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; e.target.value = ""; if (!file) return; setError(""); try { if (file.size > 10 * 1024 ** 2) throw Error("Preset supérieur à 10 Mo."); const preset = parsePreset(losslessJson(await file.text())); store([{ ...preset, id: crypto.randomUUID() }, ...items]); setMessage(`« ${preset.name} » importé.`); } catch (error) { setError(String(error)); } }} /></label></div>
    {(message || undo) && <div className="preset-feedback"><span role="status">{message}</span>{undo && <button onClick={() => action(() => { store([undo, ...items]); setUndo(null); setMessage("Preset restauré."); })}><RotateCcw size={16} /> Annuler la suppression</button>}</div>}
  </Modal>}{creating && open && <Modal title="Nouveau preset" className="new-preset-dialog" onClose={() => setCreating(false)}><form onSubmit={e => { e.preventDefault(); save(); }}><label>Titre du preset<input autoFocus maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="Portrait doux, paysage cinématique…" /></label>{error && <p role="alert">{error}</p>}<div className="row"><button type="button" onClick={() => setCreating(false)}>Annuler</button><button className="primary" type="submit" disabled={!name.trim()}>Enregistrer</button></div></form></Modal>}</>;
}
